[theme]
primaryColor = "#FF4B4B"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#262730"
textColor = "#FAFAFA"
font = "sans serif"

[server]
maxUploadSize = 200
enableXsrfProtection = false
enableCORS = true
headless = true
port = 8501
baseUrlPath = ""

[browser]
gatherUsageStats = false
serverAddress = "localhost"
serverPort = 8501

[runner]
magicEnabled = true
fastReruns = true

[logger]
level = "debug"
messageFormat = "%(asctime)s - %(name)s - %(levelname)s - [%(threadName)s] - %(message)s"

[client]
showErrorDetails = true
toolbarMode = "minimal"
caching = true

[global]
developmentMode = false
disableWatchdogWarning = true
suppressDeprecationWarnings = true 