[theme]
primaryColor = "#FF4B4B"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#262730"
textColor = "#FAFAFA"
font = "sans serif"

[server]
maxUploadSize = 200
enableXsrfProtection = false
enableCORS = true

[browser]
gatherUsageStats = false

[runner]
magicEnabled = true

[logger]
level = "info"

[client]
showErrorDetails = true
toolbarMode = "minimal"

[global]
developmentMode = false 